sudo: false
cache: cargo
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=1
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo --version
  - rustc --version
  - cargo build --verbose
  - cargo test --verbose
