cache:
  directories:
    - $HOME/.cargo
before_cache:
  # Caching takes too long.
  - rm -rf $HOME/.cargo/registry
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=full
matrix:
  fast_finish: false
  include:
  - rust: nightly
    name: "Test nightly feature"
    script: .ci/test.sh nightly
  - rust: stable
    name: "Build check Linux musl"
    script: .ci/build_check.sh "x86_64-unknown-linux-musl"
  - rust: stable
    name: "Build check Android"
    script: .ci/build_check.sh "aarch64-linux-android"
  - rust: stable
    name: "Build check NetBSD"
    script: .ci/build_check.sh "x86_64-unknown-netbsd"
  - rust: stable
    name: "Build check no features"
    script: cargo build --no-default-features
  - rust: nightly
    name: "Build check user_space feature"
    script: cargo build --no-default-features --features user_space
  - rust: nightly
    name: "Clippy check"
    # Failing the `cognitive-complexity' lint is allowed because the tests are
    # too complex.
    script: cargo clippy --all-targets --features "std nightly" -- -D warnings -A clippy::cognitive-complexity
language: rust
rust:
  - 1.33.0
  - stable
  - beta
  - nightly
script: .ci/test.sh
