cache: cargo
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=full
matrix:
  fast_finish: false
language: rust
rust:
  - 1.31.1
  - stable
  - beta
  - nightly
script:
  - cargo --version
  - rustc --version
  - |
      if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        cargo test --verbose
      else # Linux.
        cargo test --verbose --features disable_test_ipv6
      fi
