sudo: false
cache: cargo
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=1
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
language: rust
rust:
# - stable # Enable once Rust 2018 compiles on stable.
  - beta
  - nightly
script:
  - cargo --version
  - rustc --version
  - cargo test --verbose
