cache: cargo
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=full
matrix:
  fast_finish: false
  include:
  - rust: stable
    name: "Build check Linux musl"
    script: .ci/build_check.sh "x86_64-unknown-linux-musl"
  - rust: stable
    name: "Build check no features"
    script: cargo build --no-default-features
language: rust
rust:
  - 1.31.1
  - stable
  - beta
  - nightly
# Enable IPv6 on Linux machines.
before_script: [ "$TRAVIS_OS_NAME" = "linux" ] && sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script: .ci/test.sh
