sudo: false
cache: cargo
os:
  - linux
  - osx
env:
  - RUST_BACKTRACE=full
matrix:
  fast_finish: false
language: rust
rust:
# - stable # Enable once Rust 2018 compiles on stable.
  - beta
  - nightly
script:
  - cargo --version
  - rustc --version
  - |
      if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        cargo test --verbose --features disable_test_deadline
      else # Linux.
        cargo test --verbose --features disable_test_ipv6
      fi
