[package]
name          = "mio-st"
version       = "0.2.1"
authors       = ["Carl Lerche <me@carllerche.com>", "Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
license       = "MIT"
description   = "Single threaded, lightweight non-blocking IO"
readme        = "README.md"
documentation = "https://docs.rs/mio-st"
homepage      = "https://github.com/Thomasdezeeuw/mio-st"
repository    = "https://github.com/Thomasdezeeuw/mio-st"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
include       = ["Cargo.toml", "src/**/*.rs", "LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "Thomasdezeeuw/mio-st", branch = "master" }

[dependencies]
arrayvec = { version = "0.4.7", default-features = false, features = ["use_union"] }
libc     = "0.2.44"
log      = "0.4.6"

[dev-dependencies]
env_logger = "0.6.0"

[features]
# Travis doesn't support IPv6, so we disable the tests for it.
disable_test_ipv6 = []
# Travis' macOS machines don't always meet the set deadline, this disables the
# tests with strict deadlines.
disable_test_deadline = []
