[package]
name          = "mio"
version       = "0.1.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>", "Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
description   = "Single threaded, lightweight non-blocking IO"
documentation = "https://docs.rs/mio-st"
homepage      = "https://github.com/Thomasdezeeuw/mio-st"
repository    = "https://github.com/Thomasdezeeuw/mio-st"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]

[dependencies]
log      = "0.3.1"
net2     = "0.2.29"
bitflags = "1.0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2.19"

[dev-dependencies]
env_logger = { version = "0.4.0", default-features = false }

[[test]]
name = "test"
path = "test/mod.rs"
