[package]
name          = "mio-st"
version       = "0.1.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>", "Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
description   = "Single threaded, lightweight non-blocking IO"
documentation = "https://docs.rs/mio-st"
homepage      = "https://github.com/Thomasdezeeuw/mio-st"
repository    = "https://github.com/Thomasdezeeuw/mio-st"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]

[features]
default = []

# This is only used in testing timeout. Currently only used in Travis for macOS.
test_extended_time_margin = []

[dependencies]
bitflags = "1.0.1"
log      = "0.4.1"
net2     = "0.2.31"

[dependencies.arrayvec]
version = "0.4.7"
default-features = false
features = ["use_union"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.36"

[dev-dependencies]
env_logger = "0.5.3"

[[test]]
name = "test"
path = "test/mod.rs"
