[package]
name          = "mio-st"
version       = "0.1.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>", "Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
description   = "Single threaded, lightweight non-blocking IO"
readme        = "README.md"
documentation = "https://docs.rs/mio-st"
homepage      = "https://github.com/Thomasdezeeuw/mio-st"
repository    = "https://github.com/Thomasdezeeuw/mio-st"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
include       = ["Cargo.toml", "src/**/*.rs", "LICENSE"]
edition       = "2018"

[badges]
travis-ci = { repository = "https://github.com/Thomasdezeeuw/mio-st", branch = "master" }

[dependencies]
bitflags = "1.0.4"
log      = "0.4.6"
net2     = "0.2.33"

[dependencies.arrayvec]
version = "0.4.7"
default-features = false
features = ["use_union"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.44"

[dev-dependencies]
env_logger = "0.6.0"

[[test]]
name = "test"
path = "test/mod.rs"
